### PR TITLE
style: use actual booleans in install_hammer.sh

### PR DESCRIPTION
**Pull request by doclic**
IEEE POSIX has true & false commands meant for this exact purpose.

### CODE REVIEW

**Review by JJL772 — APPROVED** [review]
Thanks!

**Comment by JJL772** [comment]
Looks like this has a merge conflict and needs to be rebased locally

**Comment by doclic** [comment]
> Looks like this has a merge conflict and needs to be rebased locally

Sure, give me a few minutes

**Comment by doclic** [comment]
Resolved merge conflicts

**Comment by JJL772** [comment]
Thanks!

**Pull request merged**
