### PR TITLE
feat: Add steampath.py utility for getting app install directories

### PR DESCRIPTION
**Pull request by JJL772**
Small utility for finding appid install dirs

### CODE REVIEW

**Comment by doclic** [comment]
>Maybe we could try to set it up to use Proton? We can parse libraryfolders.vdf to find the install location of Proton. Unfortunately this would mean that moving your Proton install dir would break the installed shortcut.

We could find the path to Proton using this script when starting hammer instead of when installing the dependencies by setting the `.desktop` file's `Exec` key to something similar to this:
```desktop
Exec=sh -c "STEAM_COMPAT_CLIENT_INSTALL_PATH="$HOME/.steam" STEAM_COMPAT_DATA_PATH='/path/to/wineprefix/' \"$(./sdk_tools/util/steampath.py -a 1493710)/proton\" waitforexitandrun bin/win64/hammer.exe -winecompat"
```

Another solution is to have an option that disables DirectX rendering to child windows entirely, the easiest way to implement this would probably just be to render to a separate window but this doesn't sound very easy to use. You could probably make this better by removing `WS_CHILD` from every window, and go full-in on being multi-window.
I obviously can't test this (unless I do very naughty things with CS:GO), but I think it's a neat idea.

**Comment by JJL772** [comment]
> We could find the path to Proton using this script when starting hammer instead of when installing the dependencies by setting the .desktop file's Exec key to something similar to this:

Not a bad idea, but I'll have to think up a way to manage these python scripts. This script relies on the vdf library being installed. I could probably use `zipapp` from the standard library to package this into a single portable binary, or something like that. Would suck to add another build step though.

Alternatively, install-hammer.sh could create a venv with the vdf package installed and then execute out of there. Installing packages globally with pip is no longer supported on most distros and we can't rely on the user having conda installed or anything.

> Another solution is to have an option that disables DirectX rendering to child windows entirely

Yeah, that's an option, but I don't know if it'll be possible once we port the main window to Qt.

**Comment by doclic** [comment]
> Not a bad idea, but I'll have to think up a way to manage these python scripts. This script relies on the vdf library being installed. I could probably use `zipapp` from the standard library to package this into a single portable binary, or something like that. Would suck to add another build step though.
> 
> Alternatively, install-hammer.sh could create a venv with the vdf package installed and then execute out of there. Installing packages globally with pip is no longer supported on most distros and we can't rely on the user having conda installed or anything.

I think creating a virtual environment is the best solution, since it allows us to update dependencies independently from this repo, and it doesn't add a build step.

> > Another solution is to have an option that disables DirectX rendering to child windows entirely
> 
> Yeah, that's an option, but I don't know if it'll be possible once we port the main window to Qt.

[`QWindow` has a `setVulkanInstance` function](https://doc.qt.io/qt-6/qwindow.html#setVulkanInstance) which you can probably use. You could then probably link with dxvk, and get the `VkInstance` for your DirectX context. I didn't read the hammer source code, but I assume there isn't much more Windows specific code, and since attaching `VkSurface`s to child windows with `winex11.drv` is what's breaking everything, a native build using dxvk & qt should actually fix our problems.

I still think multi-window hammer is a neat idea and workaround in the meantime.


edit: I just realized you specifically mentioned porting the "main window" to qt, I'm not quite sure what you mean by that, could you please clarify?

**Comment by JJL772** [comment]
Sorry for the late response.

> edit: I just realized you specifically mentioned porting the "main window" to qt, I'm not quite sure what you mean by that, could you please clarify?

Main window means the main frame, so the thing that actually contains the viewports. That is still MFC for the time being. Most of the other dialogs, including the texture browser, have been ported or are in the process of being ported. Once the main window is done porting to Linux will be much easier (albeit, a lot of work).

**Review by ozxybox — APPROVED** [review]

**Pull request merged**
